// libmp4v2:/src/itmf/type.h

namespace libmp4.net
{
    /// <summary>
    /// enumerated genre as defined in ID3v1 specification but +1 as per iTMF spec.
    /// Note values 80 and higher are Winamp extensions.
    /// </summary>
    public enum MusicGenre : byte
    {
        Undefined = 0,

        /* ID3v1 standard */
        Blues = 1,
        Classic_Rock = 2,
        Country = 3,
        Dance = 4,
        Disco = 5,
        Funk = 6,
        Grunge = 7,
        Hip_Hop = 8,
        Jazz = 9,
        Metal = 10,
        New_Age = 11,
        Oldies = 12,
        Other = 13,
        Pop = 14,
        R_And_B = 15,
        Rap = 16,
        Reggae = 17,
        Rock = 18,
        Techno = 19,
        Industrial = 20,
        Alternative = 21,
        Ska = 22,
        Death_Metal = 23,
        Pranks = 24,
        Soundtrack = 25,
        Euro_Techno = 26,
        Ambient = 27,
        Trip_Hop = 28,
        Vocal = 29,
        Jazz_Funk = 30,
        Fusion = 31,
        Trance = 32,
        Classical = 33,
        Instrumental = 34,
        Acid = 35,
        House = 36,
        Game = 37,
        Sound_Clip = 38,
        Gospel = 39,
        Noise = 40,
        Alternrock = 41,
        Bass = 42,
        Soul = 43,
        Punk = 44,
        Space = 45,
        Meditative = 46,
        Instrumental_Pop = 47,
        Instrumental_Rock = 48,
        Ethnic = 49,
        Gothic = 50,
        Darkwave = 51,
        Techno_Industrial = 52,
        Electronic = 53,
        Pop_Folk = 54,
        Eurodance = 55,
        Dream = 56,
        Southern_Rock = 57,
        Comedy = 58,
        Cult = 59,
        Gangsta = 60,
        Top_40 = 61,
        Christian_Rap = 62,
        Pop_Funk = 63,
        Jungle = 64,
        Native_American = 65,
        Cabaret = 66,
        New_Wave = 67,
        Psychedelic = 68,
        Rave = 69,
        Showtunes = 70,
        Trailer = 71,
        Lo_Fi = 72,
        Tribal = 73,
        Acid_Punk = 74,
        Acid_Jazz = 75,
        Polka = 76,
        Retro = 77,
        Musical = 78,
        Rock_And_Roll = 79,

        /* Winamp extension */
        Hard_Rock = 80,
        Folk = 81,
        Folk_Rock = 82,
        National_Folk = 83,
        Swing = 84,
        Fast_Fusion = 85,
        Bebob = 86,
        Latin = 87,
        Revival = 88,
        Celtic = 89,
        Bluegrass = 90,
        Avantgarde = 91,
        Gothic_Rock = 92,
        Progressive_Rock = 93,
        Psychedelic_Rock = 94,
        Symphonic_Rock = 95,
        Slow_Rock = 96,
        Big_Band = 97,
        Chorus = 98,
        Easy_Listening = 99,
        Acoustic = 100,
        Humour = 101,
        Speech = 102,
        Chanson = 103,
        Opera = 104,
        Chamber_Music = 105,
        Sonata = 106,
        Symphony = 107,
        Booty_Bass = 108,
        Primus = 109,
        Porn_Groove = 110,
        Satire = 111,
        Slow_Jam = 112,
        Club = 113,
        Tango = 114,
        Samba = 115,
        Folklore = 116,
        Ballad = 117,
        Power_Ballad = 118,
        Rhythmic_Soul = 119,
        Freestyle = 120,
        Duet = 121,
        Punk_Rock = 122,
        Drum_Solo = 123,
        A_Capella = 124,
        Euro_House = 125,
        Dance_Hall = 126
    };
}
